# Site
#repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Personal info
name: Ramkarthik Krishnamurthy
title: Software Engineer
email: ramkarthikkrishnamurthy@gmail.com
#phone: Your phone number (optional)
#website: https://kramkarthik.com
blog: https://kramkarthik.com

# Social links
twitter_username: Ramkarthik
github_username:  Ramkarthik
#dribbble_username: jekyll
#facebook_username: jekyll
#flickr_username: jekyll
#instagram_username: jekyll
linkedin_username: ramkarthik-krishnamurthy-091978169
stackoverflow_username: 3280771/ramkarthik
#xing_username: jekyll
#pinterest_username: jekyll
#youtube_username: jekyll
#googleplus_username: +jekyll

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/ram.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Ramkarthik Krishnamurthy. I'm a software engineer with over 7 years experience. I currently live in Salt Lake City, Utah. I primarily work with <mark>C#</mark>, <mark>ASP .NET</mark> (and I love <mark>dotnet core</mark>), <mark>SQL</mark> and <mark>JavaScript</mark>. For data access, I have used both <mark>ADO .NET</mark> and <mark>EntityFramework</mark>. I have experience creating <mark>MVC</mark>, <mark>Web API</mark>, <mark>WCF</mark>, <mark>class library</mark> and <mark>console</mark> applications. Apart from this, I have also worked with <mark>SignalR</mark> and <mark>WPF</mark>.
  As for CI/CD tools, I have used <mark>Jenkins</mark>, <mark>Docker</mark>, <mark>AppVeyor</mark> and <mark>Azure Pipelines</mark>.

  There are some things I really enjoy and look for at a workplace:
  - Working with a team to create solid and easy to use products for users
  - Learning new things and taking more responsibilites
  - Automating stuff that can be automated
  - Writing lot of tests (I use <mark>MSTest</mark> and <mark>Xunit</mark>)
  - Frequent deployments

# Projects Section
# projects_title: Projects #(Use this to override about projects section title)

# Experience Section
# experience_title: Experience #(Use this to override about experience section title)

# Education Section
# educaton_title: Education #(Use this to override about education section title)

# More Section
more_title: When I'm not programming
more_content: | # this will include new lines to allow paragraphs
  I play soccer regularly and watch English Premier League (Manchester United fan). I also like to write. While I don't publish most of the things that I write, I do publish some technical articles and thoughts on [my blog](https://kramkarthik.com).

  I learnt [Carnatic music](https://en.wikiquote.org/wiki/Carnatic_music) for two years and have won some competitions when I was in school. But once I went to college, I got more into soccer and stopped taking Carnatic lessons.

  Apart from these, I love to read a lot. I mostly read about philosophy, self-help, culture and business.

# Footer
footer_show_references: true

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
